#- name: Reboot host
#  reboot:
#    reboot_timeout: 3600

- name: Reboot host
  become: true
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  ignore_errors: true

- name: Wait reboot
  become: false
  local_action:
    module: wait_for
      host={{ inventory_hostname }}
      port=22
      delay=10