#- name: Reboot host
#  reboot:
#    reboot_timeout: 3600

- name: Reboot host
  shell: "sleep 10 && reboot"
  async: 1
  poll: 0
  ignore_errors: true

- name: Wait for server to restart
  local_action:
    module: wait_for
      host={{ inventory_hostname }}
      port=22
      delay=10